import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar with chatbot documentation
  tutorialSidebar: [
    'index',
    'intro',
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI',
      items: [
        'chapter1/index',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Embodied Intelligence',
      items: [
        'chapter2/index',
        'chapter2/embodied-foundations',
        'chapter2/humanoid-design',
        'chapter2/applications',
        'chapter2/challenges',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Sensors and Actuators',
      items: [
        'chapter3/index',
        'chapter3/sensor-fundamentals',
        'chapter3/actuator-technologies',
        'chapter3/integration',
        'chapter3/applications',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: ROS2 Control Systems',
      items: [
        'chapter4/index',
        'chapter4/ros2-fundamentals',
        'chapter4/control-architecture',
        'chapter4/integration',
        'chapter4/applications',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5: AI Perception',
      items: [
        'chapter5/index',
        'chapter5/ai-perception',
        'chapter5/perception-action-loop',
        'chapter5/sensor-integration',
        'chapter5/integration-architectures',
        'chapter5/action-systems',
        'chapter5/case-studies',
        'chapter5/challenges-future',
      ],
    },
  ],
};

export default sidebars;
